<?php

/**
 * Extract vehicles from "Vehicle Papers Status" xlsx (unzipped to storage/app/temp-xlsx/).
 *
 * Columns: A S.No | B Vehicle Name | C Registration Number | D Model/Year
 * E Purchase | F Registration | G CC | H Fuel | I Purchase Value
 * J Fitness | K Taxtoken | L Insurance | M Route Permit | N Registration status
 * O Unit | P Type
 */

$base = dirname(__DIR__, 3) . '/storage/app/temp-xlsx';

if (! is_dir($base)) {
    fwrite(STDERR, "Missing {$base}. Unzip the workbook there first.\n");
    exit(1);
}

$sst = simplexml_load_file("{$base}/xl/sharedStrings.xml");
$strings = [];

foreach ($sst->si as $si) {
    if (isset($si->t)) {
        $strings[] = trim((string) $si->t);
        continue;
    }

    $text = '';
    foreach ($si->r as $run) {
        $text .= (string) $run->t;
    }
    $strings[] = trim($text);
}

$sheet = simplexml_load_file("{$base}/xl/worksheets/sheet1.xml");
$rows = [];

foreach ($sheet->sheetData->row as $row) {
    $cells = [];

    foreach ($row->c as $cell) {
        $ref = (string) $cell['r'];
        $col = preg_replace('/[0-9]+/', '', $ref);
        $value = (string) $cell->v;

        if ((string) $cell['t'] === 's') {
            $value = $strings[(int) $value] ?? '';
        }

        $cells[$col] = trim($value);
    }

    $rows[] = $cells;
}

$vehicles = [];

for ($i = 1, $count = count($rows); $i < $count; $i++) {
    $row = $rows[$i];
    $regNumber = $row['C'] ?? '';

    if ($regNumber === '') {
        continue;
    }

    $routePermit = $row['M'] ?? '';
    $regStatus = strtolower(trim($row['N'] ?? ''));

    $vehicles[] = [
        'name'                      => $row['B'] ?? '',
        'reg_number'                => $regNumber,
        'model_year'                => ($row['D'] ?? '') !== '' ? (int) $row['D'] : null,
        'purchase_date'             => ($row['E'] ?? '') !== '' ? $row['E'] : null,
        'registration_date'         => ($row['F'] ?? '') !== '' ? $row['F'] : null,
        'engine_cc'                 => ($row['G'] ?? '') !== '' ? (int) $row['G'] : null,
        'fuel_type'                 => ($row['H'] ?? '') !== '' ? $row['H'] : null,
        'purchase_value'            => ($row['I'] ?? '') !== '' ? $row['I'] : null,
        'fitness_expires_at'        => ($row['J'] ?? '') !== '' ? $row['J'] : null,
        'tax_token_expires_at'      => ($row['K'] ?? '') !== '' ? $row['K'] : null,
        'insurance_expires_at'      => ($row['L'] ?? '') !== '' ? $row['L'] : null,
        'route_permit_expires_at'   => ($routePermit === '' || strcasecmp($routePermit, 'N/A') === 0) ? null : $routePermit,
        'registration_paper_status' => $regStatus === 'ok' ? 'ok' : ($regStatus === '' ? 'ok' : 'pending'),
        'type'                      => strtolower($row['P'] ?? 'own') === 'rental' ? 'rental' : 'own',
        'passenger_capacity'        => 5,
        'status'                    => 'available',
        '_unit'                     => ($row['O'] ?? '') !== '' ? $row['O'] : null,
    ];
}

$output = "<?php\n\n/** Auto-generated by extract_tms_vehicles.php */\n\nreturn " . var_export($vehicles, true) . ";\n";
file_put_contents(dirname(__DIR__) . '/data/tms_vehicles.php', $output);

echo 'Exported ' . count($vehicles) . " vehicles\n";
